# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ff3925e0d0668763d9a42de7795544b5956c3564da1eba99714d806c81c7287ed0187303357b4c3b2c90a56de6e39a2bdb5c40457a727e662e1dbcc577a179

test:
  secret_key_base: d7b361634cda78e75c52e2464acd5fdeab5e41ac11ac5446b98e302d577f234a72cdeed356387ffc1aa68852dd06b4b37d5355efef07ab1219687f01205bd632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
